### ISSUE TITLE
Network Variable Issues

### ISSUE THREAD

**Issue by AsuDev2** [TheLimeGlass/Skungee#15]
Tested network variables on Version: 1.0.7a​ (Bungee/Spig 1.12.2) and a few things don't work. Saving the variables and list variables work fine but deleting them or removing from list variables does not work.

Ex.
delete network variable {test::*} - this does not work and the values stay the same

Ex. 2
loop network variable {test::*}: - Loop works fine
    remove loop-value from network variable {test::*} - Does not work

**Comment by TheLimeGlass** [comment]
Fixed deleting lists `delete network variable {test::*}`

Investigating remove loop-value now.

**Comment by TheLimeGlass** [comment]
Fixed
