### ISSUE TITLE
Network Variables not setting correctly

### ISSUE THREAD

**Issue by Romanthefrog10** [TheLimeGlass/Skungee#16]
I recently got Skungee and I got it all setup and I was gonna do a staff chat and I tried adding a toggle thing using variables and it works fine without network variable but whenever I set a network variable it has trouble setting it here's my code if you want to test it and see the issue for urself or if u don't get what I mean

https://pastebin.com/jG9k8BMn

You can see it works fine with "set {AO.Chat.Toggle2.%player%} to" but not with "set **network variable** {AO.Chat.Toggle2.%player%} to" but if i dont add network variable it wont do it globally...
If you want to see how it's not setting u can get it to message the player the value and u can see it doesn't change but sometimes it will but rarely

I hope this gets fixed soon! =D

**Comment by TheLimeGlass** [comment]
Problem is variables with expressions not working for some strange reason.

**Comment by TheLimeGlass** [comment]
Cannot reproduce on 1.0.7f

**Comment by TheLimeGlass** [comment]
I haven't fixed it, it just worked.

**Comment by Romanthefrog10** [comment]
Have you tested it a few times like multiple times? I thought I worked once
and after a while, it stops working
