### ISSUE TITLE
Error starting the server

### ISSUE THREAD

**Issue by MrCrazyKill** [TheLimeGlass/Skungee#17]
Hello, I installed the plugin and I config the plugin spigot and bungeecord but when I start the server, the server crash at the first start and then when it restarts alone it does not crash but I can't use the plugin effects
MC Server version: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Bungeecord build number: 1119

Here is the error:
`20.08 02:57:02 [Server] SEVERE Aug 20, 2018 2:57:02 AM net.md_5.bungee.event.EventBus post
20.08 02:57:02 [Server] INFO WARNING: Error dispatching event ProxyPingEvent(connection=[/78.205.40.20:56685] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=BungeeCord 1.8, protocol=47), players=ServerPing.Players(max=100, online=0, sample=null), description=StarkMC - MOTD en attente, favicon=null, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener me.limeglass.skungee.bungeecord.listeners.EventListener@11c9af63
20.08 02:57:02 [Server] INFO java.lang.NoSuchFieldError: SUPPORTED_VERSION_IDS
20.08 02:57:02 [Server] INFO at me.limeglass.skungee.bungeecord.listeners.EventListener.onPing(EventListener.java:64)
20.08 02:57:02 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20.08 02:57:02 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20.08 02:57:02 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20.08 02:57:02 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:221)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:199)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:231)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:29)
20.08 02:57:02 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
20.08 02:57:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
20.08 02:57:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
20.08 02:57:02 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
20.08 02:57:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
20.08 02:57:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
20.08 02:57:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
20.08 02:57:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
20.08 02:57:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
20.08 02:57:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
20.08 02:57:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:216)
20.08 02:57:02 [Server] INFO at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)`

Thanks.

**Comment by TheLimeGlass** [comment]
Update your Bungeecord.

**Comment by MrCrazyKill** [comment]
Okey i've update my Bungeecord and did all changes, work good !

But i've new error with Skellett... new post https://github.com/TheLimeGlass/Skungee/issues/18

(sorry for my english i'm french)
