### ISSUE TITLE
%event bungeecord player% returns "<none>" on bungeecord disconnect

### ISSUE THREAD

**Issue by RepublicanSensei** [TheLimeGlass/Skungee#19]
%event bungeecord player% returns "<none>" on bungeecord disconnect

**Comment by RepublicanSensei** [comment]
@TheLimeGlass

**Comment by TheLimeGlass** [comment]
Skungee and Skript need to be installed together, there is not getting around that. It's a Skript addon and it needs Skript to function.

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.7e
