### ISSUE TITLE
Waterfall Compatibility

### ISSUE THREAD

**Issue by DeibisAle** [TheLimeGlass/Skungee#20]
Good complement, but is it compatible with WaterFall?

**Comment by TheLimeGlass** [comment]
I have not tested with Waterfall, it's not supported yet, but may work. Will put in works.

**Comment by TheLimeGlass** [comment]
I just ran a test with Waterfall for the first time and I found that it works fine. I will be using Waterfall and Bungeecord for testing from now on 1.0.8 and up.
