### ISSUE TITLE
The color disappears during a line break

### ISSUE THREAD

**Issue by Vulqa** [TheLimeGlass/Skungee#27]
Everything is said in the title, when I send a colored bungeecord message to a player, once the 2nd reached line the color disappears

Skungee's version: 1.0.7d

**Comment by TheLimeGlass** [comment]
This is Bungeecord, split the lines at the colour and send two messages.

**Comment by TheLimeGlass** [comment]
I can't determine the string colours either without grabbing the initial string non colour formatted.
