### ISSUE TITLE
skungee is not showing variables right way

### ISSUE THREAD

**Issue by ham1255** [TheLimeGlass/Skungee#29]
like it if you do this
```
!add "&a", "&b", "&c", "&d", "&e", "&1", "&2", "&3", "&4", "&5", "&6", "&7", "&8", "&9" and "&f" to network variable {servers::*}
```
is does add and works when 
```
!send "network variable {servers::*}"
```
but when doing 
```
network variable {servers::1}
```
it's return <none>
https://cdn.discordapp.com/attachments/425381687308845066/515147449594019842/unknown.png

**Comment by ham1255** [comment]
it's retrun <none>

**Comment by TheLimeGlass** [comment]
You can't do indexes on variables, there is no support for handling indexes without reflection.
