### ISSUE TITLE
Proxy String Casting Error

### ISSUE THREAD

**Issue by CodaMacroft** [TheLimeGlass/Skungee#3]
So, when you try to do this in Skript [set {_SkyblockStatus} to the online status of bungeecord server "SkyBlock1"], it sends the error below. I have tried many different methods of doing this but non have worked. When I try this and it sends the error to the Proxy console, it legs all server connected to the BungeeCord. I would also like to note that I am using the variable in a GUI. I hope this gets fixed! 

20:24:27 [SEVERE] Exception in thread "Thread-3257"
20:24:27 [SEVERE] java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String
20:24:27 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.PacketHandler.handlePacket(PacketHandler.java:350)
20:24:27 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.SocketRunnable.run(SocketRunnable.java:75)
20:24:27 [SEVERE]     at java.lang.Thread.run(Thread.java:748)

**Comment by TheLimeGlass** [comment]
https://github.com/TheLimeGlass/Skungee/projects/1#card-7860724
