### ISSUE TITLE
problem with skungee in server when reloading a script

### ISSUE THREAD

**Issue by ham1255** [TheLimeGlass/Skungee#31]
![image](https://user-images.githubusercontent.com/34905970/49014951-205d2400-f19b-11e8-97b0-09fa779e6b01.png)

**Comment by TheLimeGlass** [comment]
Please provide the command log, I need to see the full error log, this image doesn't provide much useful information.

**Comment by TheLimeGlass** [comment]
Fixed a similar issue in 1.0.7e
