### ISSUE TITLE
Support for symbols in global scripts.

### ISSUE THREAD

**Issue by HevelMc** [TheLimeGlass/Skungee#32]
Hello, I noticed that you can't put accents in global script files.

An error is regularly spammed in the bungeecord console.

`13:40:20 [SEVERE] java.nio.charset.MalformedInputException: Input length = 1
13:40:20 [SEVERE]     at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
13:40:20 [SEVERE]     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
13:40:20 [SEVERE]     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
13:40:20 [SEVERE]     at java.io.InputStreamReader.read(InputStreamReader.java:184)
13:40:20 [SEVERE]     at java.io.BufferedReader.fill(BufferedReader.java:161)
13:40:20 [SEVERE]     at java.io.BufferedReader.readLine(BufferedReader.java:324)
13:40:20 [SEVERE]     at java.io.BufferedReader.readLine(BufferedReader.java:389)
13:40:20 [SEVERE]     at java.nio.file.Files.readAllLines(Files.java:3205)
13:40:20 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.ServerTracker.globalScripts(ServerTracker.java:100)
13:40:20 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.ServerTracker.update(ServerTracker.java:80)
13:40:20 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:31)
13:40:20 [SEVERE]     at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeHandler.callPacket(SkungeeHandler.java:67)
13:40:20 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.SocketRunnable.run(SocketRunnable.java:87)
13:40:20 [SEVERE]     at java.lang.Thread.run(Thread.java:748)`

Can you help me?

**Comment by TheLimeGlass** [comment]
Potentially fixed in 1.0.7e, let me know if it still occurs, if so can you please provide your global scripts from the bungeecord Skungee folder.

**Comment by HevelMc** [comment]
No; I updated the plugin on the server and the bungeecord, but always this error as soon as I put an accent.
I don't understand because with a local server backup everything works fine.
Do you have any idea why this can only happen on the vps?

**Comment by TheLimeGlass** [comment]
Support for adjusting the Charset has been added in the next version https://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html

**Comment by HevelMc** [comment]
I have upgraded the plugin to the last version and updated the line
`Charset: "default"` to `Charset: "UTF-8"` in the bungeecord config file but now, when I send messages with accentueted characters (e.g **é** or **»**) a question mark is displayed. Any Idea ?

**Comment by TheLimeGlass** [comment]
UTF-8 is the default on most systems you will need to lookup which character set your symbol belongs in and use that one.
