### ISSUE TITLE
Server out of date when trying to connect

### ISSUE THREAD

**Issue by DanRocsMinecraft** [TheLimeGlass/Skungee#33]
So when I ping the server, it says that the server is out of date and Idk why... (This is not my server). The owner says that she set the version number and made sure the server icon is 64x64, so we dont know what the issue is.

**Comment by TheLimeGlass** [comment]
This is an issue with the Bungeecord software if you're using Bungeecord. Make sure you're using the latest 1.13 snapshot of Bungeecord even if your server isn't 1.13. This is just the Bungeecord version name.

**Comment by DanRocsMinecraft** [comment]
The server is using 1.13 bungeecord @TheLimeGlass

**Comment by DanRocsMinecraft** [comment]
I don’t know if waterfall is the issue

**Comment by DanRocsMinecraft** [comment]
The server is still connectable, but we don’t like the red X that is there when we ping the server @TheLimeGlass

**Comment by TheLimeGlass** [comment]
The red has nothing to do with Skungee. Try using just Bungeecord because your server doesn't like Waterfall.
