### ISSUE TITLE
Support for UTF-8 not working?

### ISSUE THREAD

**Issue by Padlick01** [TheLimeGlass/Skungee#40]
I used symbols in my globalscripts like "»", the coding of my script is set to UTF-8, the config option is UTF-8, but when I look into the scripts Skungee copies to all of my server, there are all symbols from UTF-8 converted into "?"

Script in my globalscripts folder:
![grafik](https://user-images.githubusercontent.com/44584223/50523079-7d1b6980-0ace-11e9-87e9-e8358ff2886c.png)

Script in other server:
![grafik](https://user-images.githubusercontent.com/44584223/50523116-9d4b2880-0ace-11e9-9eb2-b61f2f760685.png)

How I said, the config option is set to use UTF-8.
![grafik](https://user-images.githubusercontent.com/44584223/50523146-be137e00-0ace-11e9-8267-cd44be54e2e8.png)

Skungee version: latest, 1.0.9

**Comment by TheLimeGlass** [comment]
UTF-8 does not contain this symbol, use a different charset

Duplicate
