### ISSUE TITLE
Skungee does not work on pterodactyl panel

### ISSUE THREAD

**Issue by ham1255** [TheLimeGlass/Skungee#43]
Well i got idea to install pterodactyl panel so i can manage my mc server But i found out that skungee does not work all like it doesnt connect to bungeecord [Waterfall]

**Comment by ham1255** [comment]
spigot server "[21:42:11 INFO]: [Skungee] Reciever established on port 1024" 
`> [21:42:12 INFO]: [Skungee] Going into keep alive mode...
`

**Comment by ham1255** [comment]
config in spigot server
```
# Skungee (Spigot) - The #1 Skript addon for Bungeecord.

# The version is to help determine which version this config is. Please don't modify this value.
version: "1.0.7f"

# Print additional information in the console. The developers of Skungee may ask you to enable this when reporting an error.
debug: false

# Ignores the packets that spam alot such as GLOBALSCRIPTS and HEARTBEAT in the debug.
# Developers of Skungee may notify you to disable this option when reporting an error.
IgnoreSpamPackets: true

# The details of the Skungee Bungeecord plugin. Place the same login credentials as the Bungeecord Skungee here.
host: "0.0.0.0"
port: 1337
```
bungeecord log and config
[21:41:56 INFO]: [Skungee] connection established on port 1337
[21:41:56 INFO]: [Skungee] has been enabled!

```
# Skungee (Bungeecord) - The #1 Skript addon for Bungeecord.

# The version is to help determine which version this configuration is. Please do not modify this value.
version: "1.0.7f"

# This is the main port for the Skungee network system. Skungee will setup this port on this Bungeecord machine.
# Make sure the port is "port forward" or that you have access to this port to be running, if not change this to an available port.

# If you don't know what ports you can access, contact your hosting company and ask for some ports.
# You can say "May I get some Votifier ports" to make it more clear to them, and they should give you a few ports. Normally all 4 digit ports above 1000 are available to you.
# Just be advised if it doesn't work, the ports aren't avalible or are already in use.

# Make sure all the port options of the Skungee's on the connected Spigot servers are matching this.
port: 1337

# Prints additional information in the console. The developers of Skungee may ask you to enable this when reporting an error.
debug: false

# Ignores the packets that spam such as GLOBALSCRIPTS and HEARTBEAT in the debug.
# Developers of Skungee may notify you to disable this option when reporting an error.
IgnoreSpamPackets: true
```

**Comment by TheLimeGlass** [comment]
When you use 0.0.0.0 you need to set an external IP to map to 0.0.0.0 which probably isn't set. Use 127.0.0.1 or "localhost". When it's set to localhost, Skungee will scan all the network IP addresses and bind to an available one. Try both, also use the latest Skungee version on both Bungeecord and Spigot, until the latest version is used, this issue will be marked as invalid.

**Comment by Nekoli** [comment]
If you're using Pterodactyl Panel you need to use the docker's IP for the host, 172.18.0.1 should be the default. You should also disable the automatic receiver port feature and set a permanent port and allocate it to that server through the panel, then don't forget to allow it through your firewall.

**Comment by TheLimeGlass** [comment]
Closing this as originally stated it's a configuration issue, thanks @Nekoli for clarifying the specifics.
