### ISSUE TITLE
Skungee evaluate not working

### ISSUE THREAD

**Issue by APickledWalrus** [TheLimeGlass/Skungee#5]
Hello. Whenever I try to use the evaluate effect with a set server, it doesn't work. I've turned on debug, and when I run the command I get:

[18:02:35] [Craft Scheduler Thread - 29/INFO]: [0;30;1m[[0;31;1mSkungee[0;30;1m] [0;33;1m[0;36;1mSending Recieved packet: EVALUATE with data: [broadcast "[0;33;22mTEST!"] with settable data: [Guilds][m
(sorry for it being messy)

The code for the command is:
`skungee eval skript code "broadcast ""&6TEST!""" on "Guilds"`

Replacing "Guilds" with the actual IP doesn't work either.
Thanks!

**Comment by TheLimeGlass** [comment]
You need to define the ip:port like that.

Also send the debug of the Bungeecord and your configurations.

**Comment by APickledWalrus** [comment]
I think I did that when I tried the IP. Here’s my configurations:

Bungee: https://pastebin.com/W292LNX1
Server: https://pastebin.com/nCFtzA3J

**Comment by TheLimeGlass** [comment]
The issue is not related to evaluate, but the error has been fixed from another error with similar remarks. I still have no clue how evaluate isn't working. I have tested on Linux and Windows servers in three different locations and they all have evaluate working fine.
