### ISSUE TITLE
Network variables with list variables don't work

### ISSUE THREAD

**Issue by joshwenke** [TheLimeGlass/Skungee#8]
Version: 1.0.6a

Syntax:
```
on script load:
	clear {network.afk::joshwenke}         <-- this DOES work
	clear {network.afk::*}         <-- doesn't work, so I tried the below
	loop network variable {network.afk::*}:       <-- still doesn't work
		clear network variable {network.afk::%loop-index%}
```

Error is "Network Variables must be in a variable format!"

**Comment by TheLimeGlass** [comment]
It works on some objects but others it doesn't, it's very strange and hard to implement. It's been on the todo list in the progress tab https://github.com/TheLimeGlass/Skungee/projects/1

I will look into fixing it soon.
